DRB/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DRB.Models;
using EF.Models;

namespace DRB.Controllers
{
    [AreaAuthentication]
    public class AboutController : Controller
    {
        public ActionResult Index(int id = 0)
        {
            using (var db = new drbContext())
            {
                var data = db.SettingsTb.Find((byte)1);
                if (id == 1)
                {
                    string msg = "تم الحفظ بنجاح";
                    if(Request.Cookies.FirstOrDefault(x => x.Key == "Lang").Value=="en")
                        msg = "Saved Successfully";
                    ViewBag.success = msg;
                    ViewBag.error = "";
                }
                else if (id == 99)
                {
                    string msg = "حدث خطأ برجاء المحاوله في وقت لاحق";
                    if (Request.Cookies.FirstOrDefault(x => x.Key == "Lang").Value == "en")
                        msg = "Error, try again later";
                    ViewBag.success = "";
                    ViewBag.error = msg;
                }
                return View(data);
            }
        }
        [HttpPost]
        public ActionResult Index(SettingsTb data)
        {
            try
            {
                using (var db = new drbContext())
                {
                    var obj = db.SettingsTb.Find((byte)1);
                    obj.AboutAppDescAr = data.AboutAppDescAr;
                    obj.AboutAppNameAr = data.AboutAppNameAr;
                    data = null;
                    db.SaveChanges();
                    return RedirectToAction("index", new { id = 1 });
                }
            }
            catch (Exception)
            {
                return RedirectToAction("index", new { id = 99 });
            }
        }
    }
}

DRB/Views/About/Index.cshtml
@model EF.Models.SettingsTb

@{
    ViewBag.Title = "من نحن";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-heading">
    <div>من نحن <small></small></div>
</div>
<div class="card card-default">
    <div class="card-heading"><h2> </h2></div>
    <div class="card-body">
        @using (Html.BeginForm("Index", "About", FormMethod.Post, new { @id = "LogForm" }))
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="text-align:center">
                    @if (ViewBag.success != null && ViewBag.success != "")
                    {
                        <div class="alert alert-success alert-dismissible fade show"><button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><b> @ViewBag.success </b></div>
                    }
                    @if (ViewBag.error != null && ViewBag.error != "")
                    {
                        <div class="alert alert-danger alert-dismissible fade show"><button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><b> @ViewBag.error </b></div>
                    }
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AboutAppNameAr, "العنوان", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.AboutAppNameAr, new { @class = "form-control DESCAR" })
                    @Html.ValidationMessageFor(model => model.AboutAppNameAr, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AboutAppDescAr, "الوصف", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.AboutAppDescAr, new { @class = "form-control DESCAR2" })
                    @Html.ValidationMessageFor(model => model.AboutAppDescAr, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="text-align:center">
                    <input type="submit" value="حفظ" onclick="formsubmit(); return false;" class="btn btn-info" />
                </div>
            </div>
        </div>
        }
    </div>
</div>

@section scripts{
    <style>
        .DESCAR, .DESCAR2 {
            height: 180px !important;
        }
    </style>
    <script src="~/AdminArea/modules/about-contact-terms-module1.0.js"></script>
}