DRB/Controllers/StringsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DRB.Models;
using EF.Models;

namespace DRB.Controllers
{
    [AreaAuthentication]
    public class StringsController : Controller
    {
        public ActionResult Index(int id = 0)
        {
            using (var db = new drbContext())
            {
                var data = db.SettingsTb.Find((byte)1);
                if (id == 1)
                {
                    string msg = "تم الحفظ بنجاح";
                    if (Request.Cookies.FirstOrDefault(x => x.Key == "Lang").Value == "en")
                        msg = "Saved Successfully";
                    ViewBag.success = msg;
                    ViewBag.error = "";
                }
                else if (id == 99)
                {
                    string msg = "حدث خطأ برجاء المحاوله في وقت لاحق";
                    if (Request.Cookies.FirstOrDefault(x => x.Key == "Lang").Value == "en")
                        msg = "Error, try again later";
                    ViewBag.success = "";
                    ViewBag.error = msg;
                }
                return View(data);
            }
        }
        [HttpPost]
        public ActionResult Index(SettingsTb data)
        {
            try
            {
                using (var db = new drbContext())
                {
                    var obj = db.SettingsTb.Find((byte)1);

                    obj.SystemProfitPercentagePerOrder = data.SystemProfitPercentagePerOrder;
                    obj.SystemProfitFromOrderCancel = data.SystemProfitFromOrderCancel;

                    obj.DriverPointsPerEachOrder= data.DriverPointsPerEachOrder;
                    
                    obj.MarchantDefaultShippingPrice = data.MarchantDefaultShippingPrice;

                    data = null;
                    db.SaveChanges();
                    return RedirectToAction("index", new { id = 1 });
                }
            }
            catch (Exception)
            {
                return RedirectToAction("index", new { id = 99 });
            }
        }
    }
}

DRB/Views/Strings/Index.cshtml
@model EF.Models.SettingsTb

@{
    ViewBag.Title = "متغيرات النظام";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-heading">
    <div>متغيرات النظام<small></small></div>
</div>
<div class="card card-default">
    <div class="card-heading"><h2> </h2></div>
    <div class="card-body">
        @using (Html.BeginForm("Index", "Strings", FormMethod.Post, new { @id = "LogForm" }))
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="text-align:center">
                    @if (ViewBag.success != null && ViewBag.success != "")
                    {
                        <div class="alert alert-success alert-dismissible fade show"><button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><b> @ViewBag.success </b></div>
                    }
                    @if (ViewBag.error != null && ViewBag.error != "")
                    {
                        <div class="alert alert-danger alert-dismissible fade show"><button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><b> @ViewBag.error </b></div>
                    }
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SystemProfitPercentagePerOrder, "نسبة التطبيق على كل طلب", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SystemProfitPercentagePerOrder, new { htmlAttributes = new { @class = "form-control AR3" } })
                    @Html.ValidationMessageFor(model => model.SystemProfitPercentagePerOrder, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SystemProfitFromOrderCancel, "مكسب التطبيق على الغاء الطلب", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SystemProfitFromOrderCancel, new { htmlAttributes = new { @class = "form-control AR4" } })
                    @Html.ValidationMessageFor(model => model.SystemProfitFromOrderCancel, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DriverPointsPerEachOrder, "نقاط المندوب من كل طلب", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DriverPointsPerEachOrder, new { htmlAttributes = new { @class = "form-control AR5" } })
                    @Html.ValidationMessageFor(model => model.DriverPointsPerEachOrder, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MarchantDefaultShippingPrice, "قيمة التوصيل الإفتراضية لأي تاجر", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MarchantDefaultShippingPrice, new { htmlAttributes = new { @class = "form-control AR6" } })
                    @Html.ValidationMessageFor(model => model.MarchantDefaultShippingPrice, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="text-align:center;">
                    <input type="submit" value="حفظ" onclick="formsubmitStrings(); return false;" class="btn btn-info" />
                </div>
            </div>

        </div>
        }
    </div>
</div>

@section scripts{
    <script src="~/AdminArea/modules/about-contact-terms-module1.0.js"></script>
}